import {CODES,KINDS,LABELS,parse,iso,add,diff,fmt,today,validDate,initialState,shift,dependsOn,validateTask,due,summary,dateSpan,saveTask,removeTask,restoreTask,holiday,validateState,recurrenceDate,recurrenceOffset,isCycleTask,swapCandidates,changeShift,originalShift,restoreShiftCandidates,resetShift} from './model.js';
import {openStore,readState,writeState} from './storage.js';
import {startupState} from './initial-data.js';
import {setupPWA} from './pwa.js';
const root=document.getElementById('agenda-preview');
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID();
let state=initialState(),selected=today(),person='me',year=parse(selected).getUTCFullYear(),month=parse(selected).getUTCMonth(),team=false,weekStart=monday(selected),page='calendar',editId=null,pickedDates=[],busy=false;
const channel='BroadcastChannel'in window?new BroadcastChannel('agenda-smeraldo'):null;
if(channel)channel.onmessage=()=>announce('L’agenda è cambiata in un’altra finestra. Ricarica la pagina prima di salvare altre modifiche.');
function monday(s){return add(s,-((parse(s).getUTCDay()+6)%7));}
let feedbackTimer;
function announce(s,error=false){clearTimeout(feedbackTimer);$('#ag-feedback').textContent=s;$('#ag-feedback').classList.toggle('ag-error',error);if(s)feedbackTimer=setTimeout(()=>{$('#ag-feedback').textContent='';},error?8000:3500);}
async function commit(change,message){if(busy)return false;busy=true;const copy=structuredClone(state);try{change(copy);copy.revision=state.revision+1;copy.savedAt=new Date().toISOString();await writeState(copy,state.revision);state=copy;render();announce(message);channel?.postMessage(state.revision);return true;}catch(e){announce(e.message||'Salvataggio non riuscito. I campi inseriti sono ancora disponibili.',true);return false;}finally{busy=false;}}
function showPage(p){if(page!==p)announce('');page=p;$$('[data-panel]').forEach(x=>x.hidden=x.dataset.panel!==p);$$('[data-page]').forEach(x=>{if(x.dataset.page===p)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current')});render();window.scrollTo({top:0,behavior:'instant'});}
function render(){renderCalendar();renderDetail();renderToday();renderSettings();renderSaved();$('#ag-profile-title').textContent=state.profile.name;$('#ag-profile-header').textContent=state.profile.name;$('#ag-avatar').textContent=state.profile.name.split(' ').map(x=>x[0]).slice(0,2).join('');$('#ag-welcome').hidden=!!state.roster.cycle.length;$('#ag-team').hidden=state.roster.people.length<2;$('#ag-roster-note').textContent=state.roster.cycle.length?`Ciclo di ${state.roster.cycle.length} giorni. Prospetto dal ${fmt(state.roster.start,{day:'numeric',month:'short',year:'numeric'})} al ${fmt(state.roster.sourceEnd,{day:'numeric',month:'short',year:'numeric'})}. Le altre date sono proiezioni. Una modifica non sposta la rotazione.`:'Seleziona un giorno per assegnare un turno. Puoi importare il calendario dall’area Impostazioni.';}
function renderCalendar(){const first=iso(new Date(Date.UTC(year,month,1)));$('#ag-team').textContent=team?'Solo i miei turni':'Turni di tutti';$('#ag-month').textContent=team?`${fmt(weekStart,{day:'numeric',month:'short'})} – ${fmt(add(weekStart,6),{day:'numeric',month:'short',year:'numeric'})}`:fmt(first,{month:'long',year:'numeric'}).toLocaleUpperCase('it-IT');$('#ag-team-search').hidden=!team;$('#ag-team-date').value=selected;$('#ag-range-note').textContent=team?'Tutti i colleghi · settimana':'I tuoi turni · mese';
 if(team){$('#ag-grid').innerHTML=`<div class="ag-table-scroll"><table class="ag-team-table"><caption class="sr-only">Turni di tutti i colleghi</caption><thead><tr><th scope="col">Collega</th>${Array.from({length:7},(_,i)=>{const s=add(weekStart,i);return `<th scope="col" class="${s===today()?'ag-today-column':''}">${s===today()?'<span class="ag-today-tag">Oggi</span>':''}<span class="${holiday(s)?'ag-red':''}">${fmt(s,{weekday:'short'})}<b>${parse(s).getUTCDate()}</b></span></th>`}).join('')}</tr></thead><tbody>${state.roster.people.map(p=>`<tr class="${p.id===state.roster.primaryId?'ag-my-row':''}"><th scope="row">${esc(p.name)}</th>${Array.from({length:7},(_,i)=>{const s=add(weekStart,i),c=shift(state,p.id,s);return `<td class="${s===today()?'ag-today-column':''}"><button type="button" aria-pressed="${s===selected&&p.id===person}" class="ag-chip ag-${KINDS[c]}" data-day="${s}" data-person="${p.id}" aria-label="${esc(p.name)}, ${fmt(s,{day:'numeric',month:'long'})}, ${c}">${c}</button></td>`}).join('')}</tr>`).join('')}</tbody></table></div>`;}
 else{const d=parse(first),offset=(d.getUTCDay()+6)%7,length=new Date(Date.UTC(year,month+1,0)).getUTCDate(),cells=Math.ceil((offset+length)/7)*7,start=add(first,-offset);$('#ag-grid').innerHTML=`<div class="ag-weekdays"><span>Lun</span><span>Mar</span><span>Mer</span><span>Gio</span><span>Ven</span><span>Sab</span><span class="ag-red">Dom</span></div><div class="ag-month-grid">${Array.from({length:cells},(_,i)=>{const s=add(start,i),c=shift(state,state.roster.primaryId,s),dayTasks=due(state,s),n=dayTasks.length,cycle=dayTasks.some(isCycleTask);return `<button type="button" class="ag-day ${s===selected?'ag-selected':''} ${s===today()?'ag-is-today':''} ${parse(s).getUTCMonth()!==month?'ag-out':''} ${holiday(s)?'ag-holiday':''}" data-day="${s}" data-person="${state.roster.primaryId}" aria-pressed="${s===selected}" aria-label="${fmt(s,{weekday:'long',day:'numeric',month:'long'})}, ${LABELS[c]}, ${n} impegni${holiday(s)?', '+holiday(s):''}"><span class="ag-day-number"><span class="ag-day-numeral">${parse(s).getUTCDate()}</span>${cycle?'<span class="ag-cycle-drop" role="img" aria-label="Ciclo mestruale"><svg viewBox="0 0 16 20" aria-hidden="true"><path fill="#be343b" d="M8 0C6 4 1 9 1 13a7 7 0 0 0 14 0C15 9 10 4 8 0Z"/><path fill="#fff" opacity=".6" d="M4 12c-1 3 1 5 3 5-2-1-2-3-2-5Z"/></svg></span>':''}</span><span class="ag-chip ag-${KINDS[c]}">${c}${state.overrides[state.roster.primaryId+'|'+s]?'*':''}</span><span class="ag-dots" aria-hidden="true">${'<i class="ag-task-dot"></i>'.repeat(Math.min(n,3))}</span></button>`}).join('')}</div>`;}}
function checks(where,date,count){const list=due(state,date),flag=list.filter(t=>t.checkable);$(count).textContent=flag.length?`${flag.filter(t=>state.completed[t.id+'|'+date]).length} / ${flag.length} fatte`:'Senza spunta';$(count).hidden=!list.length;$(where).innerHTML=list.length?list.map(t=>{const period=t.mode==='period'?`<span class="ag-period-line">Giorno ${recurrenceOffset(t,date)+1} di ${t.length} · ${date<recurrenceDate(t.start,1,t.every,t.unit||'days')?'periodo iniziale':'periodo previsto'}</span>`:'';const text=`<span class="ag-check-copy"><strong>${esc(t.name)}</strong><small>${esc(summary(t,state.tasks))}</small>${period}${t.checkable?'':'<span class="ag-task-type">Senza spunta</span>'}</span>`;return t.checkable?`<label class="ag-check-row ${state.completed[t.id+'|'+date]?'ag-done':''}"><input type="checkbox" data-check="${t.id}" data-date="${date}" ${state.completed[t.id+'|'+date]?'checked':''}>${text}</label>`:`<div class="ag-check-row ag-plain-row"><span class="ag-reference-marker" aria-hidden="true">◇</span>${text}</div>`;}).join(''):'<p class="ag-empty">Nessun impegno previsto.</p>';}
function renderDetail(){
 const p=state.roster.people.find(p=>p.id===person)||state.roster.people[0];person=p.id;
 const c=shift(state,person,selected);
 $('#ag-selected-label').textContent=(selected===today()?'OGGI · ':'')+fmt(selected,{weekday:'long'}).toUpperCase();
 $('#ag-selected-title').textContent=fmt(selected).toLocaleUpperCase('it-IT');$('#ag-detail-date').value=selected;
 $('#ag-day-shift').innerHTML=`<p class="ag-day-shift-summary"><span class="ag-chip ag-${KINDS[c]}">${c}</span><span>${esc(p.name)}</span>${holiday(selected)?`<span class="ag-red">${holiday(selected)}</span>`:''}</p>`;
 checks('#ag-day-tasks',selected,'#ag-detail-count');
}
function renderToday(){const date=today(),c=shift(state,state.roster.primaryId,date);$('#ag-today-date').textContent=fmt(date,{weekday:'long',day:'numeric',month:'long',year:'numeric'});$('#ag-today-title').textContent='Oggi';$('#ag-today-shift').innerHTML=`<div><p class="ag-kicker">IL TUO TURNO</p><p class="ag-note">${LABELS[c]}${state.roster.cycle.length&&(date<state.roster.start||date>state.roster.sourceEnd)?' · proiezione':''}</p></div><strong class="ag-shift-big">${c}</strong><button type="button" class="ag-button" id="ag-edit-today">Cambia</button>`;checks('#ag-today-list',date,'#ag-today-count');}
function goDate(date,id=person){if(!validDate(date))return;selected=date;person=id;year=parse(date).getUTCFullYear();month=parse(date).getUTCMonth();weekStart=monday(date);renderCalendar();renderDetail();}
function openDayMenu(date=selected,id=person){
 goDate(date,id);$('#ag-day-menu-title').textContent=fmt(selected,{weekday:'long',day:'numeric',month:'long'});
 $('#ag-menu-person').textContent=state.roster.people.find(p=>p.id===person)?.name||'';
 $('#ag-menu-reset').disabled=!Object.hasOwn(state.overrides,person+'|'+selected);$('#ag-menu-tasks').hidden=true;$('#ag-menu-tasks').innerHTML='';$('#ag-day-menu').showModal();
}
let restoringShift=false;
function openShift(restore=false){
 restoringShift=restore;$('#ag-shift-title').textContent=restore?'Ripristina turno':'Cambiare turno';$('#ag-shift-submit').textContent=restore?'Ripristina turno':'Salva turno';$('#ag-shift-label').textContent=restore?'Turno originale del ciclo':'Nuovo turno';$('#ag-shift-value').disabled=restore;
 if($('#ag-day-menu').open)$('#ag-day-menu').close();const old=shift(state,person,selected),target=restore?originalShift(state,person,selected):old;
 $('#ag-shift-context').textContent=state.roster.people.find(p=>p.id===person).name+' · '+fmt(selected)+' · '+old;
 $('#ag-shift-value').innerHTML=(target==='–'?['–']:CODES).map(c=>`<option value="${c}" ${c===target?'selected':''}>${c} · ${LABELS[c]}</option>`).join('');
 $('#ag-shift-error').textContent='';updateSwap();$('#ag-shift-dialog').showModal();
}
function updateSwap(){
 if(restoringShift){
  const candidates=restoreShiftCandidates(state,person,selected);
  $('#ag-partner-label').textContent='Ripristina anche il collega dello scambio';
  $('#ag-partner-wrap').hidden=!candidates.length;$('#ag-shift-partner').required=false;
  $('#ag-shift-partner').innerHTML='<option value="">Solo la persona selezionata</option>'+candidates.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');
  if(candidates.length===1)$('#ag-shift-partner').value=candidates[0].id;
  $('#ag-swap-note').textContent=candidates.length?'Torna al turno originale del ciclo. Verifica il collega da ripristinare insieme, oppure scegli solo la persona selezionata.':'Viene rimossa la modifica di questa data e torna il turno originale del ciclo. Gli altri giorni restano invariati.';
  $('#ag-shift-error').textContent='';return;
 }
 $('#ag-partner-label').textContent='Scambia con';
 const code=$('#ag-shift-value').value,old=shift(state,person,selected),candidates=code===old?[]:swapCandidates(state,person,selected,code);
 $('#ag-partner-wrap').hidden=!candidates.length;$('#ag-shift-partner').required=!!candidates.length;
 $('#ag-shift-partner').innerHTML=(candidates.length>1?'<option value="">Scegli il collega</option>':'')+candidates.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');
 $('#ag-swap-note').textContent=code===old?'Scegli il nuovo turno.':candidates.length?`Il collega scelto riceverà ${old} e tu riceverai ${code}, solo per questa data. Il ciclo resta invariato.`:'Nessun collega ha questo turno: la modifica riguarda solo la persona selezionata, per questa data.';
 $('#ag-shift-error').textContent='';
}
function renderSettings(){$('#ag-settings-tasks').innerHTML=state.tasks.length?state.tasks.map(t=>`<div class="ag-setting-row"><label><input type="checkbox" data-active="${t.id}" ${t.active?'checked':''} aria-label="Mostra in agenda: ${esc(t.name)}"><span class="ag-check-copy"><strong>${esc(t.name)}</strong><small>${esc(summary(t,state.tasks))}</small><span class="ag-task-type">Da flaggare? ${t.checkable?'Sì':'No'}</span>${t.reusable?'<span class="ag-task-type">Salvata per il futuro</span>':''}</span></label><div class="ag-row-actions"><button type="button" data-edit-task="${t.id}">Modifica</button><button type="button" class="ag-danger" data-delete-task="${t.id}" aria-label="Elimina ${esc(t.name)}">Elimina</button></div></div>`).join(''):'<p class="ag-empty">Non hai ancora attività. Premi Aggiungi.</p>';$('#ag-trash').innerHTML=state.trash.length?state.trash.slice().reverse().map(x=>`<div class="ag-setting-row"><span class="ag-check-copy"><strong>${esc(x.task.name)}</strong><small>Eliminata il ${fmt(x.deletedAt.slice(0,10))}</small></span><button type="button" class="ag-button" data-restore-task="${x.task.id}">Ripristina</button></div>`).join(''):'<p class="ag-empty">Nessuna attività eliminata.</p>';if(document.activeElement!==$('#ag-profile-name'))$('#ag-profile-name').value=state.profile.name;}
function renderSaved(){const saved=state.templates.map(t=>`<div class="ag-setting-row"><span class="ag-check-copy"><strong>${esc(t.name)}</strong><small>${esc(summary(t,state.tasks))}</small></span><div class="ag-row-actions"><button type="button" data-use-template="${t.id}">Usa</button><button type="button" class="ag-danger" data-remove-template="${t.id}">Rimuovi</button></div></div>`).join('');$('#ag-saved-settings').innerHTML=saved||'<p class="ag-empty">Quando aggiungi un’attività, seleziona “Salva questa attività per il futuro”.</p>';let holder=$('#ag-reusable-list');if(!holder){holder=document.createElement('div');holder.id='ag-reusable-list';$('#ag-presets').append(holder);}holder.innerHTML=state.templates.length?'<h2>Le tue attività salvate</h2>'+state.templates.map(t=>`<button type="button" class="ag-preset" data-use-template="${t.id}"><strong>${esc(t.name)}</strong><span>${esc(summary(t,state.tasks))}</span></button>`).join(''):'';}
function readForm(){const mode=$('#ag-repeat').value,old=state.tasks.find(t=>t.id===editId);return {id:editId||uid(),name:$('#ag-task-name').value.trim(),mode,date:$('#ag-once-date').value,start:mode==='period'?$('#ag-period-start').value:$('#ag-start').value,length:+$('#ag-period-length').value,unit:mode==='period'?$('#ag-period-unit').value:mode==='interval'?$('#ag-unit').value:'days',every:mode==='period'?+$('#ag-period-every').value:mode==='consecutive'?1:+$('#ag-every').value,duration:['interval','consecutive'].includes(mode)?(+$('#ag-duration').value||null):null,dates:[...pickedDates],active:old?old.active:true,checkable:$('#ag-checkable').value==='yes',parentId:mode==='relative'?$('#ag-anchor').value:null,before:+$('#ag-before').value,after:+$('#ag-after').value};}
function refreshParents(preferred=$('#ag-anchor').value){const choices=state.tasks.filter(t=>!editId||!dependsOn(state.tasks,t.id,editId));$('#ag-anchor').innerHTML='<option value="">Scegli una voce</option>'+choices.map(t=>`<option value="${t.id}">${esc(t.name)}${t.active?'':' · disattivata'}</option>`).join('');$('#ag-anchor').value=choices.some(t=>t.id===preferred)?preferred:'';}
function updateForm(){const mode=$('#ag-repeat').value,regular=['interval','consecutive'].includes(mode),relative=mode==='relative',period=mode==='period',once=mode==='once';$('#ag-once-fields').hidden=!once;$('#ag-period-fields').hidden=!period;$('#ag-pattern-fields').hidden=!regular;$('#ag-date-fields').hidden=mode!=='dates';$('#ag-relative-fields').hidden=!relative;$('#ag-every-wrap').hidden=mode!=='interval';for(const [s,on]of [['#ag-once-date',once],['#ag-period-start',period],['#ag-period-length',period],['#ag-period-every',period],['#ag-start',regular],['#ag-every',mode==='interval'],['#ag-unit',mode==='interval'],['#ag-period-unit',period],['#ag-anchor',relative],['#ag-before',relative],['#ag-after',relative]]){$(s).required=on;$(s).disabled=!on;}$('#ag-duration').required=mode==='consecutive';$('#ag-duration').disabled=!regular;$('#ag-duration-label').textContent=mode==='consecutive'?'Per quanti giorni':'Per quanti giorni (facoltativo)';if(mode==='consecutive'&&!$('#ag-duration').value)$('#ag-duration').value=7;refreshParents();$('#ag-dates-list').innerHTML=pickedDates.map(s=>`<button class="ag-date-pill" type="button" data-remove-date="${s}" aria-label="Rimuovi ${s}">${fmt(s,{day:'numeric',month:'short'})} ×</button>`).join('');const t=readForm();let text='';if(once)text=t.date?summary(t):'Scegli il giorno dell’appuntamento.';else if(period)text=t.start?summary(t):'Imposta il primo giorno del primo periodo.';else if(mode==='dates')text=pickedDates.length?summary(t):'Aggiungi una o più date.';else if(relative)text=t.parentId?summary(t,state.tasks)+', giorno di riferimento incluso.':'Scegli la voce di riferimento.';else text=t.start?summary(t):'Scegli il primo giorno.';$('#ag-form-summary').textContent=text+' '+(t.checkable?'Da flaggare: sì.':'Da flaggare: no.');const good=period&&validDate(t.start)&&Number.isInteger(t.length)&&t.length>0&&Number.isInteger(t.every)&&t.every*({days:1,months:28,years:365}[t.unit||'days'])>=t.length;$('#ag-period-preview').innerHTML=good?[0,1,2].map(i=>`<span class="ag-period-line">${i===0?'Primo periodo':'Periodo previsto'}: ${dateSpan(recurrenceDate(t.start,i,t.every,t.unit||'days'),t.length)}</span>`).join(''):'';const parent=state.tasks.find(p=>p.id===t.parentId);let anchors=[];if(parent?.active){if(parent.mode==='once')anchors=[parent.date];if(parent.mode==='dates')anchors=parent.dates.slice(0,3);if(['period','interval'].includes(parent.mode))anchors=[0,1,2].map(i=>recurrenceDate(parent.start,i,parent.every,parent.unit||'days'));}$('#ag-window-preview').textContent=relative&&anchors.length&&t.before>=0&&t.after>=0&&Number.isInteger(t.before)&&Number.isInteger(t.after)?'Prime date: '+anchors.map(s=>dateSpan(add(s,-t.before),t.before+t.after+1)).join('; '):'';$('#ag-form-error').textContent='';}
function clearForm(){editId=null;pickedDates=[];$('#ag-task-form').reset();$('#ag-add-title').textContent='Aggiungi attività';$('#ag-form-title').textContent='Aggiungi un impegno';$('#ag-form-label').textContent='NUOVA ATTIVITÀ';$('#ag-save-task').textContent='Aggiungi attività';$('#ag-cancel-task').hidden=true;$('#ag-delete-task').hidden=true;$('#ag-presets').hidden=false;$('#ag-specific').value=today();updateForm();}
function openAdd(date){clearForm();if(date)$('#ag-once-date').value=date;updateForm();showPage('add');}
function fillTask(t,edit){clearForm();editId=edit?t.id:null;$('#ag-task-name').value=t.name;$('#ag-repeat').value=t.mode;$('#ag-checkable').value=t.checkable?'yes':'no';$('#ag-reusable').checked=edit?!!t.reusable:false;$('#ag-once-date').value=edit?t.date||'':'';$('#ag-period-start').value=edit?t.start||'':'';$('#ag-start').value=edit?t.start||'':'';$('#ag-period-length').value=t.length||7;$('#ag-period-every').value=t.mode==='period'?t.every:27;$('#ag-every').value=t.every||1;$('#ag-unit').value=t.unit||'days';$('#ag-period-unit').value=t.unit||'days';$('#ag-duration').value=t.duration||'';$('#ag-before').value=t.before??3;$('#ag-after').value=t.after??3;pickedDates=edit?[...(t.dates||[])]:[];refreshParents(edit?t.parentId||'':'');if(edit){$('#ag-form-label').textContent='MODIFICA ATTIVITÀ';$('#ag-add-title').textContent='Modifica attività';$('#ag-form-title').textContent='Aggiorna l’impegno';$('#ag-save-task').textContent='Salva modifiche';$('#ag-cancel-task').hidden=false;$('#ag-delete-task').hidden=false;$('#ag-presets').hidden=true;}updateForm();showPage('add');}
function usePreset(key){const t={estetista:{name:'Estetista',mode:'once',checkable:false},yoga:{name:'Yoga',mode:'once',checkable:false},cycle:{name:'Ciclo mestruale',mode:'period',length:7,every:27,checkable:false},injection:{name:'Puntura',mode:'interval',every:14,duration:null,checkable:true}}[key];fillTask(t,false);}
function ask(title,message,button='Conferma'){return new Promise(resolve=>{const d=$('#ag-confirm');$('#ag-confirm-title').textContent=title;$('#ag-confirm-message').textContent=message;$('#ag-confirm-yes').textContent=button;d.returnValue='cancel';d.addEventListener('close',()=>resolve(d.returnValue==='confirm'),{once:true});d.showModal();});}
async function deleteTask(id){const t=state.tasks.find(t=>t.id===id);if(!t)return;const children=state.tasks.filter(a=>a.id!==id&&dependsOn(state.tasks,a.id,id));if(children.length){announce('Prima modifica o elimina le attività collegate: '+children.map(a=>a.name).join(', '),true);return;}if(await ask('Eliminare «'+t.name+'»?','La voce e le sue ricorrenze verranno rimosse dall’agenda. Potrai recuperarla da Eliminate di recente.','Elimina')){if(await commit(s=>removeTask(s,id),'Attività eliminata. Puoi ripristinarla da Impostazioni.')){clearForm();showPage('settings');}}}
function exportBackup(){const file=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download='agenda-'+today()+'.backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);announce('Backup esportato. Conservalo in un posto sicuro.');}
async function importBackup(file){if(!file)return;try{if(file.size>5000000)throw Error('Il file supera 5 MB.');const loaded=validateState(JSON.parse(await file.text()));if(await ask('Importare l’agenda?',`Il file contiene ${loaded.tasks.length} attività e ${loaded.roster.people.length} persone. Sostituisce i dati attuali su questo dispositivo; esporta prima un backup se vuoi conservarli.`,'Importa')){if(await commit(s=>{const revision=s.revision;Object.keys(s).forEach(k=>delete s[k]);Object.assign(s,loaded,{revision});},'Agenda importata.')){person=state.roster.primaryId;selected=today();year=parse(selected).getUTCFullYear();month=parse(selected).getUTCMonth();team=false;clearForm();showPage('calendar');}}}catch(e){announce(e.message||'Impossibile importare il file.',true);}finally{$('#ag-backup-file').value='';}}
root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.closeDialog){$('#'+d.closeDialog).close();return;}if(d.page){d.page==='add'?openAdd():showPage(d.page);return;}if(d.day){if(performance.now()<suppressClickUntil){e.preventDefault();return;}goDate(d.day,d.person);return;}if(d.preset){usePreset(d.preset);return;}if(d.editTask){if($('#ag-day-menu').open)$('#ag-day-menu').close();fillTask(state.tasks.find(t=>t.id===d.editTask),true);return;}if(d.deleteTask){await deleteTask(d.deleteTask);return;}if(d.restoreTask){await commit(s=>restoreTask(s,d.restoreTask),'Attività ripristinata.');return;}if(d.useTemplate){const t=state.templates.find(t=>t.id===d.useTemplate);if(t)fillTask(t,false);return;}if(d.removeTemplate){if(await ask('Rimuovere dalle attività salvate?','Gli impegni già presenti in agenda restano invariati.','Rimuovi'))await commit(s=>{s.templates=s.templates.filter(t=>t.id!==d.removeTemplate);s.tasks.forEach(t=>{if(t.id===d.removeTemplate)t.reusable=false;});},'Rimossa dalle attività riutilizzabili.');return;}if(d.removeDate){pickedDates=pickedDates.filter(s=>s!==d.removeDate);updateForm();return;}
 switch(b.id){case'ag-team':team=!team;weekStart=monday(selected);if(!team)person=state.roster.primaryId;render();break;case'ag-prev':case'ag-next':{const n=b.id==='ag-next'?1:-1;if(team)weekStart=add(weekStart,n*7);else{const d=new Date(Date.UTC(year,month+n,1));year=d.getUTCFullYear();month=d.getUTCMonth();}renderCalendar();break;}case'ag-current':case'ag-edit-today':goDate(today(),state.roster.primaryId);if(b.id==='ag-edit-today')openShift();break;
 case'ag-day-prev':goDate(add(selected,-1));break;case'ag-day-next':goDate(add(selected,1));break;
 case'ag-day-options':openDayMenu();break;case'ag-menu-shift':openShift();break;case'ag-menu-reset':openShift(true);break;
 case'ag-menu-add':$('#ag-day-menu').close();openAdd(selected);break;
 case'ag-menu-edit':{const list=due(state,selected);$('#ag-menu-tasks').hidden=false;$('#ag-menu-tasks').innerHTML=list.length?'<p class="ag-muted">Scegli l’attività da modificare (tutta la ricorrenza).</p>'+list.map(t=>`<button type="button" class="ag-button" data-edit-task="${t.id}">${esc(t.name)}</button>`).join(''):'<p class="ag-muted">Nessuna attività in questo giorno. Puoi aggiungerne una.</p>';break;}
 case'ag-add-selected':openAdd(selected);break;case'ag-new-from-settings':openAdd();break;case'ag-manage':showPage('settings');break;case'ag-delete-task':await deleteTask(editId);break;case'ag-cancel-task':clearForm();showPage('settings');break;case'ag-add-date':{const date=$('#ag-specific').value;if(validDate(date)&&!pickedDates.includes(date)){pickedDates.push(date);pickedDates.sort();updateForm();}break;}case'ag-export':exportBackup();break;case'ag-import':case'ag-import-start':$('#ag-backup-file').click();break;}
});
root.addEventListener('change',async e=>{const d=e.target.dataset;if(d.check){const checked=e.target.checked;if(!await commit(s=>{const k=d.check+'|'+d.date;if(checked)s.completed[k]=true;else delete s.completed[k];},checked?'Attività completata.':'Attività da completare.'))e.target.checked=!checked;}if(d.active){const checked=e.target.checked;if(!await commit(s=>{s.tasks.find(t=>t.id===d.active).active=checked;},checked?'Attività inclusa in agenda.':'Attività disattivata.'))e.target.checked=!checked;updateForm();}});
for(const id of ['ag-repeat','ag-start','ag-every','ag-duration','ag-checkable','ag-anchor','ag-before','ag-after','ag-once-date','ag-period-start','ag-period-length','ag-period-every','ag-unit','ag-period-unit'])$('#'+id).addEventListener('input',updateForm);
$('#ag-task-form').addEventListener('submit',async e=>{e.preventDefault();const task=readForm(),error=validateTask(task,state.tasks);if(error){$('#ag-form-error').textContent=error;return;}const reusable=$('#ag-reusable').checked,editing=!!editId;if(await commit(s=>saveTask(s,task,reusable),editing?'Attività aggiornata.':'Attività aggiunta all’agenda.')){clearForm();showPage('settings');announce(editing?'Attività aggiornata.':'Attività aggiunta all’agenda.');navigator.storage?.persist?.().catch(()=>{});}});
$('#ag-profile-form').addEventListener('submit',async e=>{e.preventDefault();const name=$('#ag-profile-name').value.trim();if(name)await commit(s=>{s.profile.name=name;s.roster.people.find(p=>p.id===s.roster.primaryId).name=name;},'Nome aggiornato.');});
$('#ag-backup-file').addEventListener('change',e=>importBackup(e.target.files[0]));
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){renderToday();renderCalendar();}});
$('#ag-team-date').addEventListener('change',e=>goDate(e.target.value));
$('#ag-detail-date').addEventListener('change',e=>goDate(e.target.value));
$('#ag-shift-value').addEventListener('change',updateSwap);
$('#ag-shift-form').addEventListener('submit',async e=>{
 e.preventDefault();const code=$('#ag-shift-value').value,partner=$('#ag-shift-partner').value;
 if(restoringShift){
  const probe=structuredClone(state);try{resetShift(probe,person,selected,partner);}catch(error){$('#ag-shift-error').textContent=error.message;return;}
  if(await commit(s=>resetShift(s,person,selected,partner),partner?'Turni originali ripristinati per entrambe le persone.':'Turno originale ripristinato.'))$('#ag-shift-dialog').close();return;
 }
 const probe=structuredClone(state);try{changeShift(probe,person,selected,code,partner);}catch(error){$('#ag-shift-error').textContent=error.message;return;}
 if(await commit(s=>changeShift(s,person,selected,code,partner),partner?'Turni scambiati per questa data. Il ciclo resta invariato.':'Turno aggiornato per questa data.'))$('#ag-shift-dialog').close();
});
// Cancel the long press on scrolling, movement, pointer cancellation or loss of focus.
let press=null,pressTimer=null,suppressClickUntil=0;
function cancelPress(){clearTimeout(pressTimer);pressTimer=null;press=null;}
$('#ag-grid').addEventListener('pointerdown',e=>{
 const b=e.target.closest('[data-day]');if(!b||e.button!==0||e.isPrimary===false)return;cancelPress();
 press={x:e.clientX,y:e.clientY,date:b.dataset.day,person:b.dataset.person};
 pressTimer=setTimeout(()=>{if(!press)return;const target=press;cancelPress();suppressClickUntil=performance.now()+800;openDayMenu(target.date,target.person);},550);
});
window.addEventListener('pointermove',e=>{if(press&&Math.hypot(e.clientX-press.x,e.clientY-press.y)>10)cancelPress();},{passive:true});
for(const event of ['pointerup','pointercancel','blur'])window.addEventListener(event,cancelPress);
window.addEventListener('scroll',cancelPress,{capture:true,passive:true});
$('#ag-grid').addEventListener('contextmenu',e=>{const b=e.target.closest('[data-day]');if(b){e.preventDefault();cancelPress();if(!$('#ag-day-menu').open)openDayMenu(b.dataset.day,b.dataset.person);}});
$('#ag-grid').addEventListener('keydown',e=>{const b=e.target.closest('[data-day]');if(b&&(e.key==='ContextMenu'||(e.shiftKey&&e.key==='F10'))){e.preventDefault();openDayMenu(b.dataset.day,b.dataset.person);}});
root.inert=true;
try{await openStore();const saved=await readState();state=startupState(saved);person=state.roster.primaryId;render();clearForm();root.inert=false;setupPWA(announce);}catch(e){root.inert=false;$('#ag-fatal').hidden=false;$('#ag-fatal').textContent='Non riesco ad aprire i dati del dispositivo. Prova una finestra normale del browser, con l’archiviazione consentita. Nessun dato è stato sovrascritto.';$$('button,input,select').forEach(x=>x.disabled=true);}
